spring:
  redis:
    host: 192.168.180.140

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://localhost:3306/test-where?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: 4195460316
  application:
    name: yb-mobile-redis
server:
  port: 8083
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
#  type-aliases-package: com.cyb.ybmobileredis.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*Mapper.xml
